<?php

return [
    'country_database_path' => storage_path('geoip/GeoLite2-Country.mmdb'),
    'city_database_path' => storage_path('geoip/GeoLite2-City.mmdb'),

    /*
    |--------------------------------------------------------------------------
    | Country to Locale Mapping
    |--------------------------------------------------------------------------
    |
    | This array maps ISO 1366 alpha-2 country codes to their respective locales.
    | You can expand this list with more countries and locales as needed.
    |
    */

    'country_locale' => [
        'AF' => 'fa',    // Afghanistan - Dari Persian, Pashto
        'AL' => 'sq',    // Albania - Albanian
        'DZ' => 'ar',    // Algeria - Arabic
        'AS' => 'en',    // American Samoa - English
        'AD' => 'ca',    // Andorra - Catalan
        'AO' => 'pt',    // Angola - Portuguese
        'AI' => 'en',    // Anguilla - English
        'AQ' => 'en',    // Antarctica - English (used internationally)
        'AG' => 'en',    // Antigua and Barbuda - English
        'AR' => 'es',    // Argentina - Spanish
        'AM' => 'hy',    // Armenia - Armenian
        'AW' => 'nl',    // Aruba - Dutch
        'AU' => 'en',    // Australia - English
        'AT' => 'de',    // Austria - German
        'AZ' => 'az',    // Azerbaijan - Azerbaijani
        'BS' => 'en',    // Bahamas - English
        'BH' => 'ar',    // Bahrain - Arabic
        'BD' => 'bn',    // Bangladesh - Bengali
        'BB' => 'en',    // Barbados - English
        'BY' => 'ru',    // Belarus - Belarusian, Russian
        'BE' => 'nl',    // Belgium - Dutch, French, German
        'BZ' => 'en',    // Belize - English
        'BJ' => 'fr',    // Benin - French
        'BM' => 'en',    // Bermuda - English
        'BT' => 'dz',    // Bhutan - Dzongkha
        'BO' => 'es',    // Bolivia - Spanish, Quechua, Aymara
        'BA' => 'bs',    // Bosnia and Herzegovina - Bosnian, Croatian, Serbian
        'BW' => 'en',    // Botswana - English
        'BR' => 'pt',    // Brazil - Portuguese
        'BN' => 'ms',    // Brunei - Malay
        'BG' => 'bg',    // Bulgaria - Bulgarian
        'BF' => 'fr',    // Burkina Faso - French
        'BI' => 'fr',    // Burundi - French, Kirundi
        'CV' => 'pt',    // Cape Verde - Portuguese
        'KH' => 'km',    // Cambodia - Khmer
        'CM' => 'fr',    // Cameroon - French, English
        'CA' => 'en',    // Canada - English, French
        'KY' => 'en',    // Cayman Islands - English
        'CF' => 'fr',    // Central African Republic - French, Sango
        'TD' => 'fr',    // Chad - French, Arabic
        'CL' => 'es',    // Chile - Spanish
        'CN' => 'zh',    // China - Chinese
        'CO' => 'es',    // Colombia - Spanish
        'KM' => 'ar',    // Comoros - Arabic, French
        'CG' => 'fr',    // Congo - French
        'CR' => 'es',    // Costa Rica - Spanish
        'HR' => 'hr',    // Croatia - Croatian
        'CU' => 'es',    // Cuba - Spanish
        'CY' => 'el',    // Cyprus - Greek, Turkish
        'CZ' => 'cs',    // Czech Republic - Czech
        'DK' => 'da',    // Denmark - Danish
        'DJ' => 'fr',    // Djibouti - French, Arabic
        'DM' => 'en',    // Dominica - English
        'DO' => 'es',    // Dominican Republic - Spanish
        'EC' => 'es',    // Ecuador - Spanish
        'EG' => 'ar',    // Egypt - Arabic
        'SV' => 'es',    // El Salvador - Spanish
        'GQ' => 'es',    // Equatorial Guinea - Spanish, French, Portuguese
        'ER' => 'ti',    // Eritrea - Tigrinya, Arabic, English
        'EE' => 'et',    // Estonia - Estonian
        'ET' => 'am',    // Ethiopia - Amharic
        'FJ' => 'en',    // Fiji - English, Fijian, Hindi
        'FI' => 'fi',    // Finland - Finnish, Swedish
        'FR' => 'fr',    // France - French
        'GA' => 'fr',    // Gabon - French
        'GM' => 'en',    // Gambia - English
        'GE' => 'ka',    // Georgia - Georgian
        'DE' => 'de',    // Germany - German
        'GH' => 'en',    // Ghana - English
        'GR' => 'el',    // Greece - Greek
        'GL' => 'kl',    // Greenland - Greenlandic
        'GD' => 'en',    // Grenada - English
        'GU' => 'en',    // Guam - English, Chamorro
        'GT' => 'es',    // Guatemala - Spanish
        'GN' => 'fr',    // Guinea - French
        'GW' => 'pt',    // Guinea-Bissau - Portuguese
        'GY' => 'en',    // Guyana - English
        'HT' => 'fr',    // Haiti - French, Haitian Creole
        'HN' => 'es',    // Honduras - Spanish
        'HU' => 'hu',    // Hungary - Hungarian
        'IS' => 'is',    // Iceland - Icelandic
        'IN' => 'hi',    // India - Hindi, English
        'ID' => 'id',    // Indonesia - Indonesian
        'IR' => 'fa',    // Iran - Persian
        'IQ' => 'ar',    // Iraq - Arabic, Kurdish
        'IE' => 'en',    // Ireland - English, Irish
        'IL' => 'he',    // Israel - Hebrew
        'IT' => 'it',    // Italy - Italian
        'JM' => 'en',    // Jamaica - English
        'JP' => 'ja',    // Japan - Japanese
        'JO' => 'ar',    // Jordan - Arabic
        'KZ' => 'kk',    // Kazakhstan - Kazakh, Russian
        'KE' => 'sw',    // Kenya - Swahili, English
        'KI' => 'en',    // Kiribati - English
        'KR' => 'ko',    // South Korea - Korean
        'KW' => 'ar',    // Kuwait - Arabic
        'KG' => 'ky',    // Kyrgyzstan - Kyrgyz, Russian
        'LA' => 'lo',    // Laos - Lao
        'LV' => 'lv',    // Latvia - Latvian
        'LB' => 'ar',    // Lebanon - Arabic, French
        'LS' => 'en',    // Lesotho - English, Sesotho
        'LR' => 'en',    // Liberia - English
        'LY' => 'ar',    // Libya - Arabic
        'LI' => 'de',    // Liechtenstein - German
        'LT' => 'lt',    // Lithuania - Lithuanian
        'LU' => 'lb',    // Luxembourg - Luxembourgish, French, German
        'MG' => 'fr',    // Madagascar - French, Malagasy
        'MW' => 'en',    // Malawi - English, Chichewa
        'MY' => 'ms',    // Malaysia - Malay
        'MV' => 'dv',    // Maldives - Dhivehi
        'ML' => 'fr',    // Mali - French
        'MT' => 'mt',    // Malta - Maltese, English
        'MH' => 'en',    // Marshall Islands - English, Marshallese
        'MR' => 'ar',    // Mauritania - Arabic
        'MU' => 'en',    // Mauritius - English, French
        'MX' => 'es',    // Mexico - Spanish
        'FM' => 'en',    // Micronesia - English
        'MD' => 'ro',    // Moldova - Romanian
        'MC' => 'fr',    // Monaco - French
        'MN' => 'mn',    // Mongolia - Mongolian
        'ME' => 'sr',    // Montenegro - Montenegrin, Serbian, Croatian, Bosnian
        'MA' => 'ar',    // Morocco - Arabic
        'MZ' => 'pt',    // Mozambique - Portuguese
        'MM' => 'my',    // Myanmar - Burmese
        'NA' => 'en',    // Namibia - English
        'NR' => 'en',    // Nauru - Nauruan, English
        'NP' => 'ne',    // Nepal - Nepali
        'NL' => 'nl',    // Netherlands - Dutch
        'NZ' => 'en',    // New Zealand - English, Maori
        'NI' => 'es',    // Nicaragua - Spanish
        'NE' => 'fr',    // Niger - French
        'NG' => 'en',    // Nigeria - English
        'NO' => 'no',    // Norway - Norwegian
        'OM' => 'ar',    // Oman - Arabic
        'PK' => 'ur',    // Pakistan - Urdu, English
        'PW' => 'en',    // Palau - Palauan, English
        'PS' => 'ar',    // Palestine - Arabic
        'PA' => 'es',    // Panama - Spanish
        'PG' => 'en',    // Papua New Guinea - English, Tok Pisin, Hiri Motu
        'PY' => 'es',    // Paraguay - Spanish, Guarani
        'PE' => 'es',    // Peru - Spanish
        'PH' => 'tl',    // Philippines - Filipino, English
        'PL' => 'pl',    // Poland - Polish
        'PT' => 'pt',    // Portugal - Portuguese
        'PR' => 'es',    // Puerto Rico - Spanish, English
        'QA' => 'ar',    // Qatar - Arabic
        'RO' => 'ro',    // Romania - Romanian
        'RU' => 'ru',    // Russia - Russian
        'RW' => 'rw',    // Rwanda - Kinyarwanda, French, English
        'KN' => 'en',    // Saint Kitts and Nevis - English
        'LC' => 'en',    // Saint Lucia - English
        'VC' => 'en',    // Saint Vincent and the Grenadines - English
        'WS' => 'sm',    // Samoa - Samoan, English
        'SM' => 'it',    // San Marino - Italian
        'ST' => 'pt',    // Sao Tome and Principe - Portuguese
        'SA' => 'ar',    // Saudi Arabia - Arabic
        'SN' => 'fr',    // Senegal - French
        'RS' => 'sr',    // Serbia - Serbian
        'SC' => 'fr',    // Seychelles - French, English, Seychellois Creole
        'SL' => 'en',    // Sierra Leone - English
        'SG' => 'en',    // Singapore - English, Malay, Tamil, Chinese
        'SK' => 'sk',    // Slovakia - Slovak
        'SI' => 'sl',    // Slovenia - Slovenian
        'SB' => 'en',    // Solomon Islands - English
        'SO' => 'so',    // Somalia - Somali, Arabic
        'ZA' => 'en',    // South Africa - 11 official languages, including English, Afrikaans, Zulu
        'ES' => 'es',    // Spain - Spanish
        'LK' => 'si',    // Sri Lanka - Sinhala, Tamil
        'SD' => 'ar',    // Sudan - Arabic, English
        'SR' => 'nl',    // Suriname - Dutch
        'SZ' => 'en',    // Swaziland - Swati, English
        'SE' => 'sv',    // Sweden - Swedish
        'CH' => 'de',    // Switzerland - German, French, Italian, Romansh
        'SY' => 'ar',    // Syria - Arabic
        'TW' => 'zh',    // Taiwan - Chinese
        'TJ' => 'tg',    // Tajikistan - Tajik, Russian
        'TZ' => 'sw',    // Tanzania - Swahili, English
        'TH' => 'th',    // Thailand - Thai
        'TL' => 'pt',    // Timor-Leste - Portuguese, Tetum
        'TG' => 'fr',    // Togo - French
        'TO' => 'to',    // Tonga - Tongan, English
        'TT' => 'en',    // Trinidad and Tobago - English
        'TN' => 'ar',    // Tunisia - Arabic
        'TR' => 'tr',    // Turkey - Turkish
        'TM' => 'tk',    // Turkmenistan - Turkmen, Russian
        'UG' => 'en',    // Uganda - English, Swahili
        'UA' => 'uk',    // Ukraine - Ukrainian
        'AE' => 'ar',    // United Arab Emirates - Arabic
        'GB' => 'en',    // United Kingdom - English
        'US' => 'en',    // United States - English
        'UY' => 'es',    // Uruguay - Spanish
        'UZ' => 'uz',    // Uzbekistan - Uzbek, Russian
        'VU' => 'bi',    // Vanuatu - Bislama, English, French
        'VE' => 'es',    // Venezuela - Spanish
        'VN' => 'vi',    // Vietnam - Vietnamese
        'YE' => 'ar',    // Yemen - Arabic
        'ZM' => 'en',    // Zambia - English
        'ZW' => 'en',    // Zimbabwe - English, Shona, Sindebele
    ],

];
